defaults:
  - simulation: stone_age
  - model: deepseek
  - logging: default
  - _self_

# Main simulation parameters
world:
  size: 64
  num_agents: 10
  # Terrain generation algorithm: simple | noise | voronoi | mixed
  terrain_algorithm: mixed

# Runtime parameters  
runtime:
  turns: 1000
  show_map_every: 0
  show_conversations: true
  timeout_per_agent: 15.0
  # Workstream B: hunger & consumption controls (backward-compatible defaults)
  hunger_growth_rate: 3.0
  auto_consume: true

# Display and output
output:
  log_level: INFO
  logs_dir: logs
  log_rotation: "10 MB"
  log_retention: "30 days"
  log_compression: "zip"
  # CLI view: pretty | fancy | compact | plain | jsonl
  mode: fancy
  emoji: true
  use_colors: true
  verbose: true
  show_agent_status: true

# Vision and perception
perception:
  vision_radius: 5
