"""
Agent base class for Project Genesis.

Agents are autonomous entities with attributes, inventory, memory, and LLM-driven decision making.
"""

import uuid
import json
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

from ..core.world import World, TerrainType


class AgentState(Enum):
    """Possible states an agent can be in"""
    IDLE = "idle"
    EXPLORING = "exploring"
    GATHERING = "gathering"
    CRAFTING = "crafting"
    SOCIALIZING = "socializing"
    BUILDING = "building"
    RESTING = "resting"
    FLEEING = "fleeing"
    FIGHTING = "fighting"


@dataclass
class AgentAttribute:
    """Represents an agent's attribute with current and maximum values"""
    current: float
    maximum: float
    
    @property
    def percentage(self) -> float:
        return self.current / self.maximum if self.maximum > 0 else 0.0
    
    def decrease(self, amount: float) -> float:
        """Decrease attribute and return actual amount decreased"""
        actual = min(amount, self.current)
        self.current = max(0, self.current - amount)
        return actual
    
    def increase(self, amount: float) -> float:
        """Increase attribute and return actual amount increased"""
        actual = min(amount, self.maximum - self.current)
        self.current = min(self.maximum, self.current + amount)
        return actual


@dataclass
class Item:
    """Represents an item in the world"""
    id: str
    name: str
    type: str  # 'resource', 'tool', 'food', 'weapon', 'building_material'
    quantity: float = 1.0
    durability: Optional[float] = None  # For tools/weapons
    properties: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Memory:
    """Represents a memory entry for an agent"""
    timestamp: int
    type: str  # 'event', 'interaction', 'discovery', 'skill_learned'
    content: Dict[str, Any]
    importance: float = 1.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'timestamp': self.timestamp,
            'type': self.type,
            'content': self.content,
            'importance': self.importance
        }


@dataclass
class Goal:
    """Represents an agent's current goal or motivation"""
    id: str
    description: str
    priority: float  # 0-1 scale
    category: str  # 'survival', 'social', 'exploration', 'achievement'
    target_position: Optional[Tuple[int, int]] = None
    target_agent: Optional[str] = None
    target_resource: Optional[str] = None
    progress: float = 0.0  # 0-1 scale
    completed: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'description': self.description,
            'priority': self.priority,
            'category': self.category,
            'target_position': self.target_position,
            'target_agent': self.target_agent,
            'target_resource': self.target_resource,
            'progress': self.progress,
            'completed': self.completed
        }


class Agent:
    """Main agent class with comprehensive capabilities"""
    
    def __init__(self, world: World, position: Tuple[int, int], name: Optional[str] = None):
        self.id = str(uuid.uuid4())[:8]
        self.name = name or f"Agent-{self.id}"
        self.world = world
        self.position = position
        
        # Core attributes
        self.attributes = {
            'health': AgentAttribute(100.0, 100.0),
            'strength': AgentAttribute(10.0, 20.0),
            'intelligence': AgentAttribute(10.0, 20.0),
            'charisma': AgentAttribute(10.0, 20.0),
            'dexterity': AgentAttribute(10.0, 20.0),
            'endurance': AgentAttribute(10.0, 20.0),
        }
        
        # Dynamic attributes (generated by Trinity)
        self.dynamic_attributes = {}
        
        # Inventory system
        self.inventory: Dict[str, Item] = {}
        self.max_inventory_weight = 50.0  # kg
        self.current_inventory_weight = 0.0
        
        # Memory system
        self.memories: List[Memory] = []
        self.max_memories = 100
        
        # Skills system
        self.skills: Dict[str, float] = {}  # skill_name -> proficiency (0-1)
        
        # Social system
        self.social_connections: Dict[str, float] = {}  # agent_id -> relationship_strength (-1 to 1)
        self.reputation: Dict[str, float] = {}  # group_id -> reputation
        
        # State and goals
        self.state = AgentState.IDLE
        self.current_goal: Optional[Goal] = None
        self.goals: List[Goal] = []
        
        # Basic needs
        self.needs = {
            'hunger': AgentAttribute(0.0, 100.0),
            'thirst': AgentAttribute(0.0, 100.0),
            'fatigue': AgentAttribute(0.0, 100.0),
            'social': AgentAttribute(0.0, 100.0),
        }
        
        # Life goals (motivations)
        self.life_goals = self._generate_life_goals()
        
        # Initialize starting inventory
        self._initialize_starting_inventory()
        
        # Initialize basic skills
        self._initialize_basic_skills()
    
    def _generate_life_goals(self) -> List[str]:
        """Generate life goals based on agent personality"""
        goals = [
            "survive_and_thrive",
            "explore_world",
            "build_community",
            "master_skills",
            "gain_knowledge"
        ]
        
        # Weight goals based on attributes
        weights = {
            "survive_and_thrive": 1.0,
            "explore_world": max(0.5, self.attributes['intelligence'].current / 20),
            "build_community": max(0.5, self.attributes['charisma'].current / 20),
            "master_skills": max(0.5, self.attributes['intelligence'].current / 20),
            "gain_knowledge": max(0.5, self.attributes['intelligence'].current / 20),
        }
        
        # Select 2-3 primary goals
        selected = sorted(weights.items(), key=lambda x: x[1], reverse=True)[:3]
        return [goal[0] for goal in selected]
    
    def _initialize_starting_inventory(self):
        """Initialize with basic starting items"""
        basic_items = [
            Item(str(uuid.uuid4())[:8], "water", "food", quantity=5.0),
            Item(str(uuid.uuid4())[:8], "berries", "food", quantity=3.0),
            Item(str(uuid.uuid4())[:8], "stone", "resource", quantity=2.0),
            Item(str(uuid.uuid4())[:8], "stick", "tool", quantity=1.0, durability=50.0),
        ]
        
        for item in basic_items:
            self.add_item(item)
    
    def _initialize_basic_skills(self):
        """Initialize with basic skills"""
        basic_skills = {
            'gathering': 0.3,
            'walking': 0.8,
            'observation': 0.5,
            'communication': 0.4,
            'crafting_basic': 0.2,
        }
        
        for skill, proficiency in basic_skills.items():
            self.skills[skill] = proficiency
    
    def add_item(self, item: Item) -> bool:
        """Add item to inventory, returns True if successful"""
        item_weight = self._get_item_weight(item)
        
        if self.current_inventory_weight + item_weight > self.max_inventory_weight:
            return False
        
        if item.id in self.inventory:
            # Stack with existing item
            existing = self.inventory[item.id]
            existing.quantity += item.quantity
        else:
            self.inventory[item.id] = item
        
        self.current_inventory_weight += item_weight
        return True
    
    def remove_item(self, item_id: str, quantity: float = 1.0) -> Optional[Item]:
        """Remove item from inventory, returns removed item or None"""
        if item_id not in self.inventory:
            return None
        
        item = self.inventory[item_id]
        removed_quantity = min(quantity, item.quantity)
        
        if item.quantity <= removed_quantity:
            del self.inventory[item_id]
            removed_item = Item(item.id, item.name, item.type, removed_quantity, item.durability, item.properties.copy())
        else:
            item.quantity -= removed_quantity
            removed_item = Item(item.id, item.name, item.type, removed_quantity, item.durability, item.properties.copy())
        
        self.current_inventory_weight -= self._get_item_weight(removed_item)
        return removed_item
    
    def _get_item_weight(self, item: Item) -> float:
        """Get weight of an item"""
        # Simple weight calculation based on type
        base_weights = {
            'resource': 1.0,
            'food': 0.5,
            'tool': 2.0,
            'weapon': 3.0,
            'building_material': 5.0,
        }
        
        base_weight = base_weights.get(item.type, 1.0)
        return base_weight * item.quantity
    
    def get_items_by_type(self, item_type: str) -> List[Item]:
        """Get all items of specific type"""
        return [item for item in self.inventory.values() if item.type == item_type]
    
    def get_item_count(self, item_name: str) -> float:
        """Get total quantity of item by name"""
        total = 0.0
        for item in self.inventory.values():
            if item.name == item_name:
                total += item.quantity
        return total
    
    def add_memory(self, memory_type: str, content: Dict[str, Any], importance: float = 1.0):
        """Add a memory to agent's memory bank"""
        memory = Memory(
            timestamp=self.world.time if hasattr(self.world, 'time') else 0,
            type=memory_type,
            content=content,
            importance=importance
        )
        
        self.memories.append(memory)
        
        # Keep only most important memories if over capacity
        if len(self.memories) > self.max_memories:
            self.memories.sort(key=lambda m: m.importance, reverse=True)
            self.memories = self.memories[:self.max_memories]
    
    def get_recent_memories(self, memory_type: Optional[str] = None, limit: int = 10) -> List[Memory]:
        """Get recent memories, optionally filtered by type"""
        memories = self.memories
        if memory_type:
            memories = [m for m in memories if m.type == memory_type]
        
        return memories[-limit:] if limit else memories
    
    def add_skill(self, skill_name: str, initial_proficiency: float = 0.0):
        """Add or improve a skill"""
        if skill_name in self.skills:
            self.skills[skill_name] = min(1.0, self.skills[skill_name] + initial_proficiency)
        else:
            self.skills[skill_name] = max(0.0, min(1.0, initial_proficiency))
    
    def improve_skill(self, skill_name: str, improvement: float = 0.01):
        """Improve skill through practice"""
        if skill_name in self.skills:
            self.skills[skill_name] = min(1.0, self.skills[skill_name] + improvement)
    
    def can_perform_action(self, action_type: str) -> bool:
        """Check if agent can perform specific action based on skills and resources"""
        # Basic health check
        if self.attributes['health'].current <= 0:
            return False
        
        # Check required skills
        required_skills = {
            'gather': 'gathering',
            'craft': 'crafting_basic',
            'build': 'building_basic',
            'hunt': 'hunting',
            'farm': 'farming',
        }
        
        if action_type in required_skills:
            skill_name = required_skills[action_type]
            if skill_name not in self.skills or self.skills[skill_name] < 0.1:
                return False
        
        return True
    
    def move_to(self, new_position: Tuple[int, int]) -> bool:
        """Move agent to new position"""
        x, y = new_position
        if 0 <= x < self.world.width and 0 <= y < self.world.height:
            # Check if new position is valid (not water)
            if self.world.get_terrain_at(new_position) != TerrainType.WATER:
                old_position = self.position
                self.position = new_position
                self.needs['fatigue'].increase(2.0)  # Movement causes fatigue
                self.add_memory('movement', {
                    'from': old_position,
                    'to': new_position,
                    'reason': 'exploration',
                    'terrain': self.world.get_terrain_at(new_position).name
                }, importance=0.3)
                return True
        return False
    
    def move_randomly(self) -> bool:
        """Move to a random adjacent valid position"""
        x, y = self.position
        possible_moves = []
        
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if dx == 0 and dy == 0:
                    continue
                new_x, new_y = x + dx, y + dy
                if 0 <= new_x < self.world.width and 0 <= new_y < self.world.height:
                    if self.world.get_terrain_at((new_x, new_y)) != TerrainType.WATER:
                        possible_moves.append((new_x, new_y))
        
        if possible_moves:
            return self.move_to(random.choice(possible_moves))
        return False
    
    def move_towards(self, target_position: Tuple[int, int]) -> bool:
        """Move one step towards the target position"""
        current_x, current_y = self.position
        target_x, target_y = target_position
        
        # Calculate direction
        dx = 1 if target_x > current_x else -1 if target_x < current_x else 0
        dy = 1 if target_y > current_y else -1 if target_y < current_y else 0
        
        # Try to move in the calculated direction
        new_position = (current_x + dx, current_y + dy)
        return self.move_to(new_position)
    
    def get_adjacent_positions(self) -> List[Tuple[int, int]]:
        """Get all adjacent valid positions"""
        x, y = self.position
        adjacent = []
        
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if dx == 0 and dy == 0:
                    continue
                new_x, new_y = x + dx, y + dy
                if 0 <= new_x < self.world.width and 0 <= new_y < self.world.height:
                    if self.world.get_terrain_at((new_x, new_y)) != TerrainType.WATER:
                        adjacent.append((new_x, new_y))
        
        return adjacent
    
    def update_needs(self, time_elapsed: float = 1.0):
        """Update agent's basic needs over time"""
        # Increase hunger and thirst over time
        self.needs['hunger'].increase(0.5 * time_elapsed)
        self.needs['thirst'].increase(0.7 * time_elapsed)
        self.needs['fatigue'].increase(0.3 * time_elapsed)
        self.needs['social'].increase(0.2 * time_elapsed)
        
        # Update health based on needs
        if self.needs['hunger'].current > 80 or self.needs['thirst'].current > 80:
            self.attributes['health'].decrease(1.0 * time_elapsed)
        
        if self.needs['fatigue'].current > 90:
            self.attributes['health'].decrease(0.5 * time_elapsed)
    
    def gather_resource(self, resource_type: str, amount: float = 1.0) -> Dict[str, Any]:
        """Gather a resource from the current position"""
        if not self.can_perform_action('gather'):
            return {"success": False, "reason": "Cannot perform gather action"}
        
        available = self.world.get_resource_at(self.position, resource_type)
        if available <= 0:
            return {"success": False, "reason": "No resource available"}
        
        # Calculate actual amount based on skill and strength
        gather_efficiency = self.skills.get('gathering', 0.1)
        max_amount = min(available, self.attributes['strength'].current * 0.5 * gather_efficiency)
        actual_amount = min(amount, max_amount)
        
        harvested = self.world.harvest_resource(self.position, resource_type, actual_amount)
        
        if harvested > 0:
            # Create item from harvested resource
            item = Item(
                id=f"{resource_type}_{self.world.time}_{self.id}",
                name=resource_type,
                type="resource",
                quantity=harvested
            )
            
            if self.add_item(item):
                # Improve gathering skill
                self.improve_skill('gathering', 0.01)
                
                self.add_memory('gathering', {
                    'resource': resource_type,
                    'amount': harvested,
                    'position': self.position
                }, importance=0.4)
                
                self.needs['fatigue'].increase(1.0)  # Gathering causes fatigue
                
                return {"success": True, "resource": resource_type, "amount": harvested}
            else:
                # Return harvested resource to world if inventory full
                self.world.resources[resource_type][self.position[1], self.position[0]] += harvested
                return {"success": False, "reason": "Inventory full"}
        
        return {"success": False, "reason": "Nothing harvested"}
    
    def consume_food(self, food_name: str = "food", amount: float = 1.0) -> Dict[str, Any]:
        """Consume food to reduce hunger"""
        # Find food items in inventory
        food_items = [item for item in self.inventory.values() 
                     if item.type == 'food' and item.name == food_name]
        
        if not food_items:
            return {"success": False, "reason": "No food available"}
        
        # Use the first available food item
        food_item = food_items[0]
        consume_amount = min(amount, food_item.quantity)
        
        removed = self.remove_item(food_item.id, consume_amount)
        if removed:
            # Reduce hunger based on food properties
            nutrition_value = food_item.properties.get('nutrition', 10.0)
            hunger_reduction = min(nutrition_value * consume_amount, self.needs['hunger'].current)
            self.needs['hunger'].decrease(hunger_reduction)
            
            self.add_memory('consumption', {
                'item': food_name,
                'amount': consume_amount,
                'hunger_reduced': hunger_reduction
            }, importance=0.3)
            
            return {"success": True, "food": food_name, "amount": consume_amount, "hunger_reduced": hunger_reduction}
        
        return {"success": False, "reason": "Failed to consume food"}
    
    def consume_water(self, amount: float = 1.0) -> Dict[str, Any]:
        """Consume water to reduce thirst"""
        # Find water items in inventory
        water_items = [item for item in self.inventory.values() 
                      if item.name == 'water']
        
        if not water_items:
            return {"success": False, "reason": "No water available"}
        
        # Use the first available water item
        water_item = water_items[0]
        consume_amount = min(amount, water_item.quantity)
        
        removed = self.remove_item(water_item.id, consume_amount)
        if removed:
            # Reduce thirst
            thirst_reduction = min(15.0 * consume_amount, self.needs['thirst'].current)
            self.needs['thirst'].decrease(thirst_reduction)
            
            self.add_memory('consumption', {
                'item': 'water',
                'amount': consume_amount,
                'thirst_reduced': thirst_reduction
            }, importance=0.3)
            
            return {"success": True, "water": consume_amount, "thirst_reduced": thirst_reduction}
        
        return {"success": False, "reason": "Failed to consume water"}
    
    def rest(self) -> Dict[str, Any]:
        """Rest to recover fatigue"""
        fatigue_reduction = min(15.0, self.needs['fatigue'].current)
        self.needs['fatigue'].decrease(fatigue_reduction)
        
        # Small health recovery
        health_recovery = min(2.0, self.attributes['health'].maximum - self.attributes['health'].current)
        self.attributes['health'].increase(health_recovery)
        
        self.add_memory('rest', {
            'fatigue_reduced': fatigue_reduction,
            'health_recovered': health_recovery,
            'position': self.position
        }, importance=0.2)
        
        return {"success": True, "fatigue_reduced": fatigue_reduction, "health_recovered": health_recovery}
    
    def get_surrounding_resources(self, radius: int = 3) -> Dict[str, List[Tuple[int, int, float]]]:
        """Get resources within a given radius"""
        resources = {}
        
        for resource_type in self.world.resources:
            positions = []
            for dx in range(-radius, radius + 1):
                for dy in range(-radius, radius + 1):
                    x = self.position[0] + dx
                    y = self.position[1] + dy
                    if 0 <= x < self.world.width and 0 <= y < self.world.height:
                        amount = self.world.get_resource_at((x, y), resource_type)
                        if amount > 0.1:
                            positions.append((x, y, amount))
            resources[resource_type] = positions
        
        return resources
    
    def find_nearest_resource(self, resource_type: str) -> Optional[Tuple[int, int]]:
        """Find the nearest position with the specified resource"""
        best_position = None
        best_distance = float('inf')
        
        for dx in range(-10, 11):  # Search within 10 tiles
            for dy in range(-10, 11):
                x = self.position[0] + dx
                y = self.position[1] + dy
                if 0 <= x < self.world.width and 0 <= y < self.world.height:
                    amount = self.world.get_resource_at((x, y), resource_type)
                    if amount > 0.1:
                        distance = abs(dx) + abs(dy)  # Manhattan distance
                        if distance < best_distance:
                            best_distance = distance
                            best_position = (x, y)
        
        return best_position
    
    def get_state_summary(self) -> Dict[str, Any]:
        """Get comprehensive summary of agent state"""
        return {
            "id": self.id,
            "name": self.name,
            "position": self.position,
            "state": self.state.value,
            "attributes": {name: attr.current for name, attr in self.attributes.items()},
            "dynamic_attributes": self.dynamic_attributes,
            "inventory": {
                item.name: {"quantity": item.quantity, "type": item.type}
                for item in self.inventory.values()
            },
            "inventory_weight": f"{self.current_inventory_weight:.1f}/{self.max_inventory_weight:.1f}",
            "skills": self.skills,
            "social_connections": len(self.social_connections),
            "memories": len(self.memories),
            "goals": [goal.to_dict() for goal in self.goals],
            "life_goals": self.life_goals,
            "needs": {name: attr.current for name, attr in self.needs.items()},
        }
    
    def __str__(self) -> str:
        return f"{self.name}({self.id}) at {self.position}"
    
    def __repr__(self) -> str:
        return f"Agent(id={self.id}, name={self.name}, pos={self.position}, health={self.attributes['health'].current})"