# @package _global_
logging:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} - {message}"
  console_format: "<level>{message}</level>"
  
  file:
    enabled: true
    path: "logs/sociology_simulation_{time}.log"
    rotation: "10 MB"
    retention: "30 days"
    compression: "zip"
  
  console:
    enabled: true
    level: INFO