"""
Skill Generator - Creates new skills based on observed behavioral patterns.

This system analyzes patterns detected by Trinity Observer and generates
new skills that agents can learn to improve their capabilities.
"""

import json
import random
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime
import hashlib

from loguru import logger


@dataclass
class GeneratedSkill:
    """Represents a skill generated by the Trinity system"""
    skill_id: str
    name: str
    description: str
    category: str  # 'gathering', 'crafting', 'social', 'combat', 'building', 'exploration'
    proficiency_range: Tuple[float, float]  # (min, max) proficiency
    prerequisites: Dict[str, Any]  # required attributes, skills, resources
    effects: Dict[str, Any]  # what this skill enables
    complexity: float  # 0-1 complexity score
    generation_reason: str  # why this skill was generated
    based_on_pattern: str  # pattern ID that triggered generation
    generation_turn: int
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'skill_id': self.skill_id,
            'name': self.name,
            'description': self.description,
            'category': self.category,
            'proficiency_range': self.proficiency_range,
            'prerequisites': self.prerequisites,
            'effects': self.effects,
            'complexity': self.complexity,
            'generation_reason': self.generation_reason,
            'based_on_pattern': self.based_on_pattern,
            'generation_turn': self.generation_turn
        }


class SkillGenerator:
    """
    Generates new skills based on observed behavioral patterns.
    
    This system creates skills that address observed needs, inefficiencies,
    or opportunities in agent behavior patterns.
    """
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.generated_skills: List[GeneratedSkill] = []
        self.skill_templates = self._load_skill_templates()
        self.generation_history: List[Dict[str, Any]] = []
        
        # Generation thresholds
        self.skill_threshold = config.get('skill_generation_threshold', 3)
        self.max_skills_per_category = config.get('max_skills_per_category', 10)
    
    def _load_skill_templates(self) -> Dict[str, List[Dict[str, Any]]]:
        """Load base skill templates for different categories"""
        return {
            'gathering': [
                {
                    'name': 'Advanced Foraging',
                    'description': 'Enhanced ability to find and gather food resources',
                    'prerequisites': {'intelligence': 12, 'gathering': 0.3},
                    'effects': {'food_gathering_efficiency': 1.5, 'food_discovery_range': 2},
                    'complexity': 0.4
                },
                {
                    'name': 'Resource Scouting',
                    'description': 'Ability to scout and map resource locations',
                    'prerequisites': {'intelligence': 15, 'observation': 0.4},
                    'effects': {'resource_detection_range': 3, 'resource_quality_bonus': 0.2},
                    'complexity': 0.5
                },
                {
                    'name': 'Efficient Harvesting',
                    'description': 'More efficient resource extraction techniques',
                    'prerequisites': {'strength': 12, 'gathering': 0.5},
                    'effects': {'harvest_amount_multiplier': 1.3, 'tool_durability_bonus': 0.1},
                    'complexity': 0.3
                }
            ],
            'crafting': [
                {
                    'name': 'Tool Making',
                    'description': 'Ability to craft basic tools from available materials',
                    'prerequisites': {'intelligence': 13, 'crafting_basic': 0.3},
                    'effects': {'tool_crafting_success_rate': 0.8, 'tool_quality_bonus': 0.2},
                    'complexity': 0.5
                },
                {
                    'name': 'Advanced Crafting',
                    'description': 'Create more complex items and tools',
                    'prerequisites': {'intelligence': 16, 'tool_making': 0.7},
                    'effects': {'advanced_item_crafting': True, 'material_efficiency': 1.2},
                    'complexity': 0.7
                },
                {
                    'name': 'Weapon Smithing',
                    'description': 'Craft weapons for hunting and defense',
                    'prerequisites': {'strength': 14, 'tool_making': 0.6, 'stone': 5},
                    'effects': {'weapon_crafting': True, 'weapon_damage_bonus': 0.3},
                    'complexity': 0.8
                }
            ],
            'social': [
                {
                    'name': 'Leadership',
                    'description': 'Ability to lead and coordinate group activities',
                    'prerequisites': {'charisma': 15, 'communication': 0.4},
                    'effects': {'group_coordination_bonus': 1.4, 'social_influence': 0.3},
                    'complexity': 0.6
                },
                {
                    'name': 'Negotiation',
                    'description': 'Skill in resolving conflicts and making deals',
                    'prerequisites': {'charisma': 13, 'intelligence': 12},
                    'effects': {'trade_efficiency': 1.5, 'conflict_resolution': 0.7},
                    'complexity': 0.5
                },
                {
                    'name': 'Teaching',
                    'description': 'Ability to teach skills to other agents',
                    'prerequisites': {'intelligence': 14, 'charisma': 12},
                    'effects': {'skill_transmission_rate': 0.8, 'learning_bonus': 1.2},
                    'complexity': 0.7
                }
            ],
            'building': [
                {
                    'name': 'Shelter Construction',
                    'description': 'Build basic shelters for protection',
                    'prerequisites': {'strength': 12, 'wood': 10},
                    'effects': {'shelter_building': True, 'defense_bonus': 0.4},
                    'complexity': 0.4
                },
                {
                    'name': 'Advanced Architecture',
                    'description': 'Build complex structures and buildings',
                    'prerequisites': {'intelligence': 16, 'shelter_construction': 0.7, 'stone': 15},
                    'effects': {'complex_building': True, 'building_efficiency': 1.5},
                    'complexity': 0.8
                }
            ],
            'exploration': [
                {
                    'name': 'Cartography',
                    'description': 'Create and read maps of the world',
                    'prerequisites': {'intelligence': 15, 'observation': 0.5},
                    'effects': {'map_making': True, 'exploration_efficiency': 1.3},
                    'complexity': 0.6
                },
                {
                    'name': 'Pathfinding',
                    'description': 'Find optimal paths between locations',
                    'prerequisites': {'intelligence': 14, 'observation': 0.4},
                    'effects': {'movement_efficiency': 1.4, 'danger_detection': 0.3},
                    'complexity': 0.5
                }
            ]
        }
    
    def generate_skills_from_patterns(self, patterns: List[Any], turn: int) -> List[GeneratedSkill]:
        """Generate new skills based on observed behavioral patterns"""
        generated_skills = []
        
        for pattern in patterns:
            if pattern.confidence >= 0.7 and pattern.frequency >= self.skill_threshold:
                skill = self._create_skill_from_pattern(pattern, turn)
                if skill and not self._skill_exists(skill.name):
                    generated_skills.append(skill)
                    self.generated_skills.append(skill)
                    
                    self.generation_history.append({
                        'turn': turn,
                        'pattern_id': pattern.pattern_id,
                        'skill_id': skill.skill_id,
                        'skill_name': skill.name,
                        'reason': skill.generation_reason
                    })
                    
                    logger.info(f"Generated new skill: {skill.name} from pattern {pattern.pattern_id}")
        
        return generated_skills
    
    def _create_skill_from_pattern(self, pattern, turn: int) -> Optional[GeneratedSkill]:
        """Create a specific skill based on a behavioral pattern"""
        
        # Map pattern types to skill categories
        category_mapping = {
            'individual': 'gathering',
            'social': 'social',
            'collective': 'building',
            'resource_usage': 'gathering',
            'movement': 'exploration'
        }
        
        category = category_mapping.get(pattern.pattern_type, 'gathering')
        
        # Get appropriate skill template
        templates = self.skill_templates.get(category, [])
        if not templates:
            return None
        
        # Select template based on pattern context
        template = self._select_template_for_pattern(pattern, templates)
        if not template:
            return None
        
        # Customize template based on pattern details
        skill_name = self._generate_skill_name(template['name'], pattern)
        skill_description = self._generate_skill_description(template['description'], pattern)
        
        # Generate unique skill ID
        skill_id = self._generate_skill_id(skill_name, turn)
        
        # Adjust prerequisites based on pattern complexity
        prerequisites = template['prerequisites'].copy()
        prerequisites = self._adjust_prerequisites(prerequisites, pattern)
        
        return GeneratedSkill(
            skill_id=skill_id,
            name=skill_name,
            description=skill_description,
            category=category,
            proficiency_range=(0.0, 1.0),
            prerequisites=prerequisites,
            effects=template['effects'],
            complexity=template['complexity'],
            generation_reason=f"Generated from {pattern.pattern_type} pattern: {pattern.description}",
            based_on_pattern=pattern.pattern_id,
            generation_turn=turn
        )
    
    def _select_template_for_pattern(self, pattern, templates: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Select the most appropriate skill template for a pattern"""
        if not templates:
            return None
        
        # Use pattern context to select template
        template_index = hash(pattern.pattern_id) % len(templates)
        return templates[template_index]
    
    def _generate_skill_name(self, base_name: str, pattern) -> str:
        """Generate a unique skill name based on pattern context"""
        # Add pattern-specific suffixes
        suffix_map = {
            'individual': 'Mastery',
            'social': 'Cooperation',
            'collective': 'Synergy',
            'resource_usage': 'Efficiency',
            'movement': 'Navigation'
        }
        
        suffix = suffix_map.get(pattern.pattern_type, 'Technique')
        return f"{base_name} {suffix}"
    
    def _generate_skill_description(self, base_description: str, pattern) -> str:
        """Generate a skill description incorporating pattern insights"""
        context_additions = {
            'individual': "Developed through repeated individual practice",
            'social': "Learned through social interaction and cooperation",
            'collective': "Mastered through group coordination and collective effort",
            'resource_usage': "Optimized through understanding of resource patterns",
            'movement': "Refined through exploration and navigation experience"
        }
        
        addition = context_additions.get(pattern.pattern_type, "Developed through experience")
        return f"{base_description}. {addition}."
    
    def _adjust_prerequisites(self, prerequisites: Dict[str, Any], pattern) -> Dict[str, Any]:
        """Adjust prerequisites based on pattern complexity and frequency"""
        adjusted = prerequisites.copy()
        
        # Increase requirements for complex/high-frequency patterns
        if pattern.confidence > 0.9:
            for key in adjusted:
                if isinstance(adjusted[key], (int, float)):
                    adjusted[key] = max(adjusted[key], adjusted[key] * 1.2)
        
        return adjusted
    
    def _generate_skill_id(self, skill_name: str, turn: int) -> str:
        """Generate a unique skill ID"""
        content = f"{skill_name}_{turn}_{datetime.now().isoformat()}"
        return hashlib.md5(content.encode()).hexdigest()[:8]
    
    def _skill_exists(self, skill_name: str) -> bool:
        """Check if a skill with this name already exists"""
        return any(skill.name == skill_name for skill in self.generated_skills)
    
    def get_available_skills(self, agent_attributes: Dict[str, float], 
                           agent_skills: Dict[str, float], 
                           agent_inventory: Dict[str, float]) -> List[GeneratedSkill]:
        """Get skills available to an agent based on their current state"""
        available_skills = []
        
        for skill in self.generated_skills:
            if self._meets_prerequisites(skill, agent_attributes, agent_skills, agent_inventory):
                available_skills.append(skill)
        
        return available_skills
    
    def _meets_prerequisites(self, skill: GeneratedSkill, 
                           agent_attributes: Dict[str, float], 
                           agent_skills: Dict[str, float], 
                           agent_inventory: Dict[str, float]) -> bool:
        """Check if an agent meets the prerequisites for a skill"""
        prerequisites = skill.prerequisites
        
        # Check attributes
        for attr_name, required_value in prerequisites.items():
            if attr_name in agent_attributes:
                if agent_attributes[attr_name] < required_value:
                    return False
            elif attr_name in agent_skills:
                if agent_skills.get(attr_name, 0) < required_value:
                    return False
            elif attr_name in agent_inventory:
                if agent_inventory.get(attr_name, 0) < required_value:
                    return False
        
        return True
    
    def get_skill_summary(self) -> Dict[str, Any]:
        """Get summary of generated skills"""
        category_counts = defaultdict(int)
        for skill in self.generated_skills:
            category_counts[skill.category] += 1
        
        return {
            'total_skills_generated': len(self.generated_skills),
            'skills_by_category': dict(category_counts),
            'recent_generations': self.generation_history[-10:],
            'all_skills': [skill.to_dict() for skill in self.generated_skills]
        }
    
    def reset_skills(self):
        """Reset all generated skills (for testing purposes)"""
        self.generated_skills.clear()
        self.generation_history.clear()